# Generated by Django 5.0.7 on 2024-08-21 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_config'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id']},
        ),
    ]
